Repository DoodlePlay/Server, pull requests merged in 2024-10, with the labels that each got.

#2 [FEAT] Socket.IO 연결 및 게임방 채팅영역 소켓 연동 #1
  src/server.js
Labels: 📬 API, ✨ Feature

#4 [FEAT] 실시간 그림 전송 및 표시 기능 구현 #3
  src/server.js
Labels: ✨ Feature

#6 [FEAT] 대기실 및 게임방 추가 작업 #5
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
  src/quizTopics.js
  src/server.js
Labels: 📬 API, 🐞 BugFix, ✨ Feature

#10 [FEAT] 아이템 사용 소켓 작업 #8
  src/server.js
Labels: 📬 API, ✨ Feature

#11 [FEAT] 게임 진행 우선 소켓 작업 #7
  src/server.js
Labels: ✨ Feature

#13 [FEAT] 게임 진행 소켓 작업 #12
  src/server.js
Labels: ✨ Feature, 🔨 Refactor

#19 [FEAT] 정답 처리 소켓 작업 #9
  .prettierrc
  .vscode/settings.json
  src/matchCounter.js
  src/server.js
Labels: ✨ Feature
