Repository DoodlePlay/Server, pull requests merged in 2024-11, with the labels that each got.

#21 [FIX] 게임 진행 버그 수정 작업 #18
  src/server.js
Labels: 🐞 BugFix, 🔨 Refactor

#24 [FIX] 게임 진행 버그 수정 #23
  src/server.js
Labels: 🐞 BugFix

#26 [FIX] 정답 처리 오류 수정 #20
  src/matchCounter.js
  src/quizTopics.js
  src/server.js
Labels: 🐞 BugFix, ✨ Feature

#29 [FEAT] 아이템 시스템 메세지 전송 및 대기실 추가 작업 #22
  src/server.js
Labels: 🐞 BugFix, ✨ Feature, ⚙Setting

#30 [FIX] 게임 진행 버그 수정 #25
  src/server.js
Labels: 🐞 BugFix

#32 [FIX] 단어 선택 시 채팅 오류 수정
  src/server.js
Labels: 🐞 BugFix
